### ISSUE TITLE
Change links color

### ISSUE THREAD

**Issue by fergus-macdubh** [fergus-macdubh/mermaid#100]
Client is not satisfied with light color of links (hardly readable on his device), so we need to make them more contrast (I suggest, deep blue would be ok).

**Comment by VeneraDomina** [comment]
@fergus-macdubh, what do you think about below colors. The first one is dark blue, but it comes out from color sheme of the site. I like the second one and the forth.
![links](https://user-images.githubusercontent.com/32742205/38671385-ef7e3400-3e53-11e8-8255-f9b077d9c59b.PNG)

**Comment by fergus-macdubh** [comment]
Let's make like in second one, or maybe darker a bit.
