### ISSUE TITLE
Closed month report

### ISSUE THREAD

**Issue by fergus-macdubh** [fergus-macdubh/mermaid#111]
We need save report values separately for each month to make reports for previous months unchanged.

1. Add new column with values (open/closed) to the report list page (it would be nice to have some sign for it).
2. Add button 'Закрыть месяц' to the current report page (for open months only).
3. Create form with predefined values (all non-order-related fields) and save data separately.
4. Show committed (non-dynamic) values for closed months.

**Comment by AlesiaPavliuchenkova** [comment]
@fergus-macdubh ,
"3. Create form with predefined values (all non-order-related fields) and save data separately."
Just want to clarify:
User with ADMIN role pushes "Закрыть месяц" button --> 
Form with option predefined values appears (options that participate in report data calculation) -->
User can change option values and push button ("Закрыть месяц") -->
All data that are used in report are calculated and saved to the table

**Comment by fergus-macdubh** [comment]
Yes, exactly 😀

сб, 5 мая 2018 г., 1:49 Alesia Pavliuchenkova <notifications@github.com>:
