### ISSUE TITLE
Отчет по покраске в выбранный цвет

### ISSUE THREAD

**Issue by Milfirin** [fergus-macdubh/mermaid#120]
Привет. Необходимо сделать такой отчет: 
Выбираем краску, задаем период. Выводим такие данные:
дата заказа
айди заказа в русалочке
номер документа
менеджер
площадь заказа
суммарная площадь покраски в этот цвет в этот период

**Comment by fergus-macdubh** [comment]
Добавить также фильтр по типу продукции (кляймеры, фурнитура, профиль)
