### ISSUE TITLE
Печатные формы

### ISSUE THREAD

**Issue by Milfirin** [fergus-macdubh/mermaid#150]
Печать наряда в работу. 

Сейчас после составления плана на день и перемещении В РАБОТУ оператор пишет бумажечки какие заказы передать, какую краску выдать, вечером смена пишет от руки табличку сколько по каким заказам реально использовано. 
Необходимо сделать печатную форму: распечатывать В РАБОТУ в виде таблички. Точнее пожелания по столбцам будут в начале недели. 

Этой же формой я предлагаю печатать и столбец НОВЫЕ в дальнейшем. Пока это не надо, но возможно понадобится для удобства.

**Comment by fergus-macdubh** [comment]
@Milfirin подготовить список колонок

**Comment by fergus-macdubh** [comment]
![image](https://user-images.githubusercontent.com/5836750/98078530-ed3d6800-1e7a-11eb-8c16-de09069de5cb.png)

**Comment by fergus-macdubh** [comment]
Выгрузка в CSV:
- Бригада и дата (заголовок)
- Документ
- Краска
- Производитель
- Норма расхода
- Выдано краски (пустая)
- Возврат краски (пустая)
- Фактический расход (пустая)

**Comment by fergus-macdubh** [comment]
@Milfirin какой порядок сортировки заказов в печатной форме?

**Comment by fergus-macdubh** [comment]
@Milfirin в заказе может быть несколько расходников (в том числе красок) - что в этом случае? Делать несколько строк для одного и того же заказа (вписывать фактический расход, выдано, получено надо будет раздельно ведь по краскам)?

**Comment by Milfirin** [comment]
Сортировать по краске, фактически мы не использовали другие расходники кроме краски.
Использовали ли две краски в одном заказе тоже не помню - возможно очень редко. Если такое есть разбить на две строки.
но мне кажестся они делят заказ на два если есть там две краски

**Comment by TamCher** [comment]
Done and push to Prod

**Comment by TamCher** [comment]
Done and push to Prod
