### ISSUE TITLE
Фильтры в страницу Заказы

### ISSUE THREAD

**Issue by Milfirin** [fergus-macdubh/mermaid#154]
1. При нажатии "Архив" очень долго грузится, и ненужные периоды с 2017 года. Надо сделать выбор периода при нажатии кнопки Архив. При выборе периода удобно если будет быстрый выбор "текущий год" или "прошлый месяц" (или если сделать выбор периода сложно, сделать несколько кнопок: 2021, 2020, 2019, 2018, 2017)

2. добавить фильтр "краска" - поиск по краске, расставить фильтры в том же порядке как колонки

3. столбец ГОТОВО (дата) перенести на третье место
4. добавить столбец ДНИ, и выводить количество дней, которое заказ был в работе (мы вроде записываем это инфо в карточку заказа)

https://mail.google.com/mail/u/0?ui=2&ik=a639938ebd&attid=0.1.2&permmsgid=msg-f:1681932642308019918&th=17576cd3b0e756ce&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ-GpLcbSkKTiVI1w1gk7ukLvufTfl-fm9buE381L9KdyxyoZLHc_D9B3cNE5MOmy9qGguqJsKdyDHRxHAqqvGkLvw7U3yQ-jtIKlIR_39tJhSwv4meZh0Yo-iw&disp=emb

**Comment by fergus-macdubh** [comment]
Колонка "дни": разница в днях между созданием заказа и датой перевода в SHIPPING
