### ISSUE TITLE
сортировка по алфавиту в форме создания-изменения заказа

### ISSUE THREAD

**Issue by Milfirin** [fergus-macdubh/mermaid#155]
В этой форме можно сделать по алфавиту выдачу?

https://mail.google.com/mail/u/0?ui=2&ik=a639938ebd&attid=0.1.1&permmsgid=msg-f:1681932642308019918&th=17576cd3b0e756ce&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ-pM9CRTJdfLew1sT0jmQJuHMp5PhQDWF81E5WY2e3s3EsmWbwIsZnO84QDcOeOtqCEhYKsyrlCbYtxXmEUaV2HYeuIT7lwXNe-2RQ7RzDQzcErDyJrb0Od1r0&disp=emb

**Comment by fergus-macdubh** [comment]
Отсортировать по алфавиту клиентов в дроп-дауне
