### ISSUE TITLE
Фильтр на канбане

### ISSUE THREAD

**Issue by Milfirin** [fergus-macdubh/mermaid#157]
Ситуация: очень много заказов НОВЫЕ, чтобы оператору составить заказ в работу из одного цвета (или одного заказчика) надо долго скроллить. Путаются и делают все вручную на листиках.

Надо или делать фильтр на КАНБАНЕ (отбор заказов по цвету, такой же как на странице заказы).
ИЛИ на странице ЗАКАЗЫ размещать кнопки запуска и вообще затачивать ее под работу оператора в основном в ней.

**Comment by fergus-macdubh** [comment]
Делаем фильтр по цвету на канбане (только для столбца НОВЫЕ)

**Comment by fergus-macdubh** [comment]
+ такой же фильтр на странице "Заказы"

**Comment by fergus-macdubh** [comment]
Сортировать новые заказы по дням просрочки
