### ISSUE TITLE
Переименование полей в отчете и опциях

### ISSUE THREAD

**Issue by fergus-macdubh** [fergus-macdubh/mermaid#163]
- Поля "Зарплата маляра" и "зарплата подсобника" переименовать на "Ставка маляра" и "Ставка подсобника"
- "Зарплата начцеха" меняем на "Ставка мастера", и "коэф мастера" (то есть начцеха назовем мастером теперь)

**Comment by TamCher** [comment]
Please, review.

**Comment by fergus-macdubh** [comment]
Approved for merging.
