### ISSUE TITLE
дата и время заказов

### ISSUE THREAD

**Issue by Milfirin** [fergus-macdubh/mermaid#34]
время оказалось очень важно. Надо выносить на канбан.

Ставим дату внесения в "новые" (создания заказа). указываем сразу плановую готовность. У нас срок 7 рабочих дней. (если с рабочими сложно, то давай впишем 7 календарных).
Было бы вообще круто, чтобы в готовых писалось сколько фактически прошло дней. можно даже не стирать плановую дату, просто писать рядом цифру(5).

![default](https://user-images.githubusercontent.com/33002875/31989723-cd45dd8c-b97b-11e7-9eef-2319279ed887.png)

**Comment by fergus-macdubh** [comment]
Ты не мог бы нарисовать как ты это видишь с примером даты и сотавшихся дней? По словесному описанию не очень понятно.

**Comment by Milfirin** [comment]
так тут картинка есть. вот я и нарисовал как вижу

**Comment by Milfirin** [comment]
немного переставить надписи, и добавить внизу строку. 
27 окт 15:06, готов на 3 ноя

**Comment by fergus-macdubh** [comment]
Я имею в виду картинку с примером данных

**Comment by Milfirin** [comment]
вот так:
![default](https://user-images.githubusercontent.com/33002875/32103892-f21c0e78-bb2a-11e7-8b93-d5475eaf96b0.png)
